version: '3.8'

services:
  bot:
    build: .
    container_name: instagram-telegram-bot
    volumes:
      - ./downloads:/app/downloads
      - ./gallery-dl-cookies.txt:/app/gallery-dl-cookies.txt:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    environment:
      - TZ=UTC
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s