services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: instagram-telegram-bot
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data:rw
      - ./sessions:/app/downloads/sessions:rw
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./telegram:/app/telegram
      - ./gallery-dl-cookies.txt:/app/gallery-dl-cookies.txt:ro
      - ./.env:/app/.env:ro
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    environment:
      - TZ=UTC
      - PATH=/usr/local/bin:$PATH
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "python", "healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    init: true  # Handle signals properly